### ISSUE TITLE
Unexpected and unhandled error during batch writing

### ISSUE THREAD

**Issue by thomas-tran** [transmute-industries/sidetree.js#165]
I tried to run the following code
const dto = {"type":"create","delta":"eyJwYXRjaGVzIjpbeyJhY3Rpb24iOiJyZXBsYWNlIiwiZG9jdW1lbnQiOnsicHVibGljX2tleXMiOlt7ImlkIjoiejZNa2dSdGEyRTJTS3MzakpxMURrMUp0NUxoQjNKZzFFMkM5M1RFTXppVW42d0RTIiwiandrIjp7ImNydiI6IkVkMjU1MTkiLCJrdHkiOiJPS1AiLCJ4IjoiSFYyQ3hEMlVoX3l6VVpiUHQ3MGp0YTZWN21uSFM4QkdOMWNwR0JKVHM2RSJ9LCJwdXJwb3NlIjpbImdlbmVyYWwiLCJhdXRoIiwiYXNzZXJ0aW9uIiwiaW52b2NhdGlvbiIsImRlbGVnYXRpb24iXSwidHlwZSI6Ikpzb25XZWJLZXkyMDIwIn0seyJpZCI6Ino2TFNpM05UQW1XZXh2ZWdUY1lmR1dKVlc2UWt2UUxnTlJKckh5SDRlTlprSFVaUiIsImp3ayI6eyJjcnYiOiJYMjU1MTkiLCJrdHkiOiJPS1AiLCJ4IjoiWHBRVXJ5alpTWkxCRlc2S2lXMmNFbjgya0pQOFI5elZxODRZTXE3RnJSUSJ9LCJwdXJwb3NlIjpbImdlbmVyYWwiLCJhZ3JlZW1lbnQiXSwidHlwZSI6Ikpzb25XZWJLZXkyMDIwIn1dLCJzZXJ2aWNlX2VuZHBvaW50cyI6W3siZW5kcG9pbnQiOiJodHRwczovL2V4YW1wbGUuY29tIiwiaWQiOiJyZXNvbHZlci0wIiwidHlwZSI6IlJlc29sdmVyIn1dfX1dLCJ1cGRhdGVfY29tbWl0bWVudCI6IkVpQTdMc2t4VTJNVllabTFKdDJrdjl1YUdJNGsxUmgza1oydE9kTEtHaVlDclEifQ","suffix_data":"eyJkZWx0YV9oYXNoIjoiRWlETm5SYmJPeGxQVjZnREthaEdmZHFxSlZzb0FUZWhZa28yYVk4aXhRc2o5ZyIsInJlY292ZXJ5X2NvbW1pdG1lbnQiOiJFaUE3THNreFUyTVZZWm0xSnQya3Y5dWFHSTRrMVJoM2taMnRPZExLR2lZQ3JRIn0"}

const newDidMethod = new DidMethod(config, version, blockchain, cas);

const response = await newDidMethod .handleOperationRequest(
        Buffer.from(JSON.stringify(dto))
    )

and I got this error 
Unexpected and unhandled error during batch writing, investigate and fix:
TypeError: Cannot read property '_id' of undefined
    at D:\Apps\testapp\node_modules\@sidetree\db\dist\db.cjs.development.js:502:33
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

If I removed below from the delta then it worked ok
  "service_endpoints": [
          {
            "endpoint": "https://example.com",
            "id": "resolver-0",
            "type": "Resolver"
          }
        ]

**Comment by thomas-tran** [comment]
Close since I forgot to add the transaction number to the anchor file
