### ISSUE TITLE
Error while running test:only @sidetree/core   

### ISSUE THREAD

**Issue by devrajsinghrawat** [transmute-industries/sidetree.js#219]
I am facing error while running this test case, Do we need to have any specific version of Node? I am running on v12.22.4

Devrajs-MacBook-Pro:~/1/evan/sidetree/sidetree.js|main ⇒  npm run test:only @sidetree/core   

> root@ test:only /Users/devd/1/evan/sidetree/sidetree.js
> npm t -- --scope "@sidetree/core"

> root@ test /Users/devd/1/evan/sidetree/sidetree.js
> lerna run test --stream --concurrency 1 "--scope" "@sidetree/core"
```
lerna notice cli v3.22.1
lerna notice filter including "@sidetree/core"
lerna info filter [ '@sidetree/core' ]
lerna info Executing command in 1 package: "npm run test"
@sidetree/core: > @sidetree/core@0.2.6-unstable.1 pretest /Users/devd/1/evan/sidetree/sidetree.js/packages/core
@sidetree/core: > docker-compose up -d mongo
@sidetree/core: The MNEMONIC variable is not set. Defaulting to a blank string.
@sidetree/core: sidetreejs_mongo_1 is up-to-date
@sidetree/core: > @sidetree/core@0.2.6-unstable.1 test /Users/devd/1/evan/sidetree/sidetree.js/packages/core
@sidetree/core: > tsdx test
@sidetree/core: PASS src/test/util/Compressor.spec.ts
@sidetree/core: PASS src/test/ValueTimeLockVerifier.spec.ts
@sidetree/core: PASS src/test/Did.spec.ts
@sidetree/core: PASS src/test/DocumentComposer.spec.ts
@sidetree/core: PASS src/test/write/MapFile.spec.ts
@sidetree/core: PASS src/test/RecoverOperation.spec.ts
@sidetree/core: PASS src/test/write/AnchorFile.spec.ts
@sidetree/core: PASS src/test/UpdateOperation.spec.ts
@sidetree/core: PASS src/test/VersionManager.spec.ts
@sidetree/core: PASS src/test/TransactionProcessor.spec.ts
@sidetree/core:   ● Console
@sidetree/core:     console.error
@sidetree/core:       Unexpected error processing transaction, MUST investigate and fix: Some unexpected error.
@sidetree/core:       109 |         return true;
@sidetree/core:       110 |       } else {
@sidetree/core:     > 111 |         console.error(
@sidetree/core:           |                 ^
@sidetree/core:       112 |           `Unexpected error processing transaction, MUST investigate and fix: ${error.message}`
@sidetree/core:       113 |         );
@sidetree/core:       114 |         return false;
@sidetree/core:       at TransactionProcessor.<anonymous> (src/TransactionProcessor.ts:111:17)
@sidetree/core:       at step (node_modules/tslib/tslib.js:140:27)
@sidetree/core:       at Object.next (node_modules/tslib/tslib.js:121:57)
@sidetree/core:       at node_modules/tslib/tslib.js:114:75
@sidetree/core:       at Object.__awaiter (node_modules/tslib/tslib.js:110:16)
@sidetree/core:       at TransactionProcessor.Object.<anonymous>.TransactionProcessor.processTransaction (src/TransactionProcessor.ts:41:24)
@sidetree/core:       at src/test/TransactionProcessor.spec.ts:288:49
@sidetree/core:     console.error
@sidetree/core:       Unexpected error fetching map file EiAekkDOQ-otibG1GQf_4TNmXVds0qEqd5-4BAtG6IwpYA, MUST investigate and fix: {"stack":"Error: Any unexpected error.\n    at SpyStrategy.throwError (/sidetree.js/packages/core/node_modules/jest-jasmine2/build/jasmine/SpyStrategy.js:113:50)\n    at /sidetree.js/packages/core/src/test/TransactionProcessor.spec.ts:590:69\n    at step (/sidetree.js/packages/core/node_modules/tslib/tslib.js:140:27)\n    at Object.next (/sidetree.js/packages/core/node_modules/tslib/tslib.js:121:57)\n    at fulfilled (/sidetree.js/packages/core/node_modules/tslib/tslib.js:111:62)","message":"Any unexpected error."}
@sidetree/core:       227 |         return undefined;
@sidetree/core:       228 |       } else {
@sidetree/core:     > 229 |         console.error(
@sidetree/core:           |                 ^
@sidetree/core:       230 |           `Unexpected error fetching map file ${
@sidetree/core:       231 |             anchorFile.model.map_file_uri
@sidetree/core:       232 |           }, MUST investigate and fix: ${SidetreeError.stringify(error)}`
@sidetree/core:       at TransactionProcessor.<anonymous> (src/TransactionProcessor.ts:229:17)
@sidetree/core:       at step (node_modules/tslib/tslib.js:140:27)
@sidetree/core:       at Object.next (node_modules/tslib/tslib.js:121:57)
@sidetree/core:       at node_modules/tslib/tslib.js:114:75
@sidetree/core:       at Object.__awaiter (node_modules/tslib/tslib.js:110:16)
@sidetree/core:       at TransactionProcessor.Object.<anonymous>.TransactionProcessor.downloadAndVerifyMapFile (src/TransactionProcessor.ts:139:24)
@sidetree/core:       at src/test/TransactionProcessor.spec.ts:597:8
@sidetree/core:     console.error
@sidetree/core:       Unexpected error fetching chunk file EiBfmkyidiSVlBFgk7hqPC1T3lyoWM25K_YCQ7WwsVxmcA, MUST investigate and fix: {"stack":"Error: Any unexpected error.\n    at SpyStrategy.throwError (/Users/sidetree.js/packages/core/node_modules/jest-jasmine2/build/jasmine/SpyStrategy.js:113:50)\n    at /Users/sidetree.js/packages/core/src/test/TransactionProcessor.spec.ts:676:69\n    at step (/Users/sidetree.js/packages/core/node_modules/tslib/tslib.js:140:27)\n    at Object.next (/Users/sidetree.js/packages/core/node_modules/tslib/tslib.js:121:57)\n    at fulfilled (/Users/sidetree.js/packages/core/node_modules/tslib/tslib.js:111:62)","message":"Any unexpected error."}
@sidetree/core:       280 |         return undefined;
@sidetree/core:       281 |       } else {
@sidetree/core:     > 282 |         console.error(
@sidetree/core:           |                 ^
@sidetree/core:       283 |           `Unexpected error fetching chunk file ${chunkFileHash}, MUST investigate and fix: ${SidetreeError.stringify(
@sidetree/core:       284 |             error
@sidetree/core:       285 |           )}`
@sidetree/core:       at TransactionProcessor.<anonymous> (src/TransactionProcessor.ts:282:17)
@sidetree/core:       at step (node_modules/tslib/tslib.js:140:27)
@sidetree/core:       at Object.next (node_modules/tslib/tslib.js:121:57)
@sidetree/core:       at node_modules/tslib/tslib.js:114:75
@sidetree/core:       at Object.__awaiter (node_modules/tslib/tslib.js:110:16)
@sidetree/core:       at TransactionProcessor.Object.<anonymous>.TransactionProcessor.downloadAndVerifyChunkFile (src/TransactionProcessor.ts:196:24)
@sidetree/core:       at src/test/TransactionProcessor.spec.ts:682:8
@sidetree/core: PASS src/test/util/Jws.spec.ts
@sidetree/core:   ● Console
@sidetree/core:     console.log
@sidetree/core:       Input 'eyJhbGciOiJFZERTQSJ9.eyJhYmMiOiJzb21lIHZhbHVlIn0.MgvF8aNZoIAZ6g2EjiNCvt6XS86bDkuW3kKp91BxGUyT5mF66bKBfBDoaYMQp-DFloov1s90Rj8DVzRrC_9VCQ' failed signature verification: Error: jws_failed_signature_validation: signature verification failed
@sidetree/core:       at Function.<anonymous> (src/util/Jws.ts:155:15)
@sidetree/core:     console.log
@sidetree/core:       Input 'some invalid string' failed signature verification: Error: jws_failed_signature_validation: Cannot read property 'toString' of undefined
@sidetree/core:       at Function.<anonymous> (src/util/Jws.ts:155:15)
@sidetree/core: PASS src/test/RequestHandler.spec.ts
@sidetree/core: PASS src/test/ThroughputLimiter.spec.ts
@sidetree/core: PASS src/__test__/cas.sanity.test.ts
@sidetree/core: PASS src/test/Response.spec.ts
@sidetree/core: PASS src/test/ServiceInfoProvider.spec.ts
@sidetree/core: PASS src/util/Compressor.test.ts
@sidetree/core: PASS src/test/FeeManager.spec.ts
@sidetree/core: PASS src/test/write/BatchWriter.spec.ts
@sidetree/core: PASS src/test/write/ChunkFile.spec.ts
@sidetree/core:   ● Console
@sidetree/core:     console.info
@sidetree/core:       Parsed chunk file in 3 ms.
@sidetree/core:       at Function.<anonymous> (src/write/ChunkFile.ts:48:13)
@sidetree/core:     console.info
@sidetree/core:       Parsed chunk file in 1 ms.
@sidetree/core:       at Function.<anonymous> (src/write/ChunkFile.ts:48:13)
@sidetree/core: PASS src/test/util/Jwk.spec.ts
@sidetree/core: PASS src/test/ietf-patch-operations.spec.ts
@sidetree/core: PASS src/test/Resolver.spec.ts
@sidetree/core:   ● Console
@sidetree/core:     console.info
@sidetree/core:       Resolving DID unique suffix 'EiCab7dkFgsiaIqYIP7zLbuer97ImyRz0sEK0pluw44JsQ'...
@sidetree/core:       at Resolver.<anonymous> (src/Resolver.ts:45:13)
@sidetree/core:     console.info
@sidetree/core:       Resolving DID unique suffix 'EiCab7dkFgsiaIqYIP7zLbuer97ImyRz0sEK0pluw44JsQ'...
@sidetree/core:       at Resolver.<anonymous> (src/Resolver.ts:45:13)
@sidetree/core:     console.log
@sidetree/core:       Skipped bad operation for DID EiDGI4XRRd-7tZ0yJoPSQA5eNkY8TLvJwCQLu9GNpaTSFg at time 1. Error: {"stack":"Error: any error\n    at SpyStrategy.throwError (/Users/sidetree.js/packages/core/node_modules/jest-jasmine2/build/jasmine/SpyStrategy.js:113:50)\n    at /Users/sidetree.js/packages/core/src/test/Resolver.spec.ts:407:46\n    at step (/Users/sidetree.js/packages/core/node_modules/tslib/tslib.js:140:27)\n    at Object.next (/Users/sidetree.js/packages/core/node_modules/tslib/tslib.js:121:57)\n    at /Users/sidetree.js/packages/core/node_modules/tslib/tslib.js:114:75\n    at new Promise (<anonymous>)\n    at Object.__awaiter (/Users/sidetree.js/packages/core/node_modules/tslib/tslib.js:110:16)\n    at Object.<anonymous> (/Users/sidetree.js/packages/core/src/test/Resolver.spec.ts:406:73)\n    at Object.asyncJestTest (/Users/sidetree.js/packages/core/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:100:37)\n    at /Users/sidetree.js/packages/core/node_modules/jest-jasmine2/build/queueRunner.js:45:12\n    at new Promise (<anonymous>)\n    at mapper (/Users/sidetree.js/packages/core/node_modules/jest-jasmine2/build/queueRunner.js:28:19)\n    at /Users/sidetree.js/packages/core/node_modules/jest-jasmine2/build/queueRunner.js:75:41","message":"any error"}
@sidetree/core:       at Resolver.<anonymous> (src/Resolver.ts:248:15)
@sidetree/core: PASS src/test/write/BatchScheduler.spec.ts
@sidetree/core: PASS src/__test__/test-fixture-generation.test.ts
@sidetree/core:   ● Console
@sidetree/core:     console.info
@sidetree/core:       Parsed chunk file in 2 ms.
@sidetree/core:       at Function.<anonymous> (src/write/ChunkFile.ts:48:13)
@sidetree/core: PASS src/test/DownloadManager.spec.ts (5.6s)
@sidetree/core: PASS src/test/MongoDbOperationStore.test.ts (7.492s)
@sidetree/core:   ● Console
@sidetree/core:     console.info
@sidetree/core:       Reusing existing collection operation
@sidetree/core:       at _callee3$ (../db/src/MongoDb.ts:76:7)
@sidetree/core:     console.info
@sidetree/core:       Reusing existing collection operation
@sidetree/core:       at _callee3$ (../db/src/MongoDb.ts:76:7)
@sidetree/core: PASS src/test/Observer.spec.ts (7.65s)
@sidetree/core: PASS src/test/OperationProcessor.spec.ts (15.744s)
@sidetree/core:   ● Console
@sidetree/core:     console.log
@sidetree/core:       Input 'eyJhbGciOiJFZERTQSJ9.eyJkZWx0YV9oYXNoIjoiRWlCdDdYd1V3NUx4aDRvbWxXNUhSNXpieUlZU3ZaaHZyLVFpTHVPRF9ETVp3USIsInVwZGF0ZV9rZXkiOnsiY3J2IjoiRWQyNTUxOSIsImtpZCI6IkFWSHdHQnB1dXViUGEtdC0yNGdsN1JYRFlXMFMxSnhkSG9nb0JfOUFTdVEiLCJrdHkiOiJPS1AiLCJ4IjoicG5QcjluMm95MUZWRXdSWEZlbmt4WlllcXBYZ3p3TWhNc1ZnWGFnN3ZfbyJ9fQ.jpIpsCtASmhQGJ7tEASXKbrVf7yhzJUp8Z4-c0I02x8ygjo6WVquPP_U8e92sHON6lS_y7KY2yp6pSoXOInhDQ' failed signature verification: Error: jws_failed_signature_validation: signature verification failed
@sidetree/core:       at Function.<anonymous> (src/util/Jws.ts:155:15)
@sidetree/core:     console.debug
@sidetree/core:       Ignored invalid operation for DID 'EiCE1E_JjLwY3pboiw3J9vOn-Fh2qz0RVRcx6QOWVcTniw' in transaction '1' at time '1' at operation index 0.
@sidetree/core:       at OperationProcessor.<anonymous> (src/OperationProcessor.ts:94:17)
@sidetree/core:     console.debug
@sidetree/core:       Ignored invalid operation for DID 'EiAAE7YkIN6t0fAyGDOu9Nyz9kP7zWOAngx-RwDOefDIZw' in transaction '2' at time '2' at operation index 2.
@sidetree/core:       at OperationProcessor.<anonymous> (src/OperationProcessor.ts:94:17)
@sidetree/core:     console.debug
@sidetree/core:       Ignored invalid operation for DID 'EiC3c5N-1dLmkmnLSFipX6LDhYkXu1HLps2eayfzRx-AUg' in transaction '2' at time '2' at operation index 2.
@sidetree/core:       at OperationProcessor.<anonymous> (src/OperationProcessor.ts:94:17)
@sidetree/core:     console.debug
@sidetree/core:       Ignored invalid operation for DID 'EiBih4upBfl660SegGb6CpYthH5beLbpd0XYaYqxfxrVmw' in transaction '2' at time '2' at operation index 2.
@sidetree/core:       at OperationProcessor.<anonymous> (src/OperationProcessor.ts:94:17)
@sidetree/core:     console.log
@sidetree/core:       Input 'eyJhbGciOiJFZERTQSJ9.eyJkZWx0YV9oYXNoIjoiRWlBYnlHR3pOcjI3YmNJQ1NpMG1QakczN3ZMYk5VWUdOamJlaTE5RVV6RGhYQSIsInVwZGF0ZV9rZXkiOnsiY3J2IjoiRWQyNTUxOSIsImtpZCI6IjlVcVo1QS03MzF4bEZQNWJ1bU9OV2R6dGNwa1Y3b2VFdWRaNTVSeGJ5RGMiLCJrdHkiOiJPS1AiLCJ4Ijoibk5WNWk2NUVEdWVaWEd0U2N5a29YZXJsM1BZOW9QUTVkMWxRbEZwWFVZWSJ9fQ.2_AuuzWM9LArhFoZTKGK-XpEx4pfqUCgkglYlcGw0D11WcpN7lgePVfsvjIJTT1Ma5TYuzhPkQc6ydFkTRhYBg' failed signature verification: Error: jws_failed_signature_validation: signature verification failed
@sidetree/core:       at Function.<anonymous> (src/util/Jws.ts:155:15)
@sidetree/core:     console.debug
@sidetree/core:       Ignored invalid operation for DID 'EiCA2UpNAy9ipewJlcNuP5NKdCiLTZKpE5HFDiOuJMcByw' in transaction '2' at time '2' at operation index 2.
@sidetree/core:       at OperationProcessor.<anonymous> (src/OperationProcessor.ts:94:17)
@sidetree/core:     console.debug
@sidetree/core:       Ignored invalid operation for DID 'EiB0bxS-BWYaKvq-31UAuFfBD6z_imRD_9N8jjqwDXVNBA' in transaction '2' at time '2' at operation index 2.
@sidetree/core:       at OperationProcessor.<anonymous> (src/OperationProcessor.ts:94:17)
@sidetree/core:     console.debug
@sidetree/core:       Ignored invalid operation for DID 'EiAbC5efUQbjSfBjk8yFXMQVZ8_GsSdmqajoAtXFucfMsQ' in transaction '2' at time '2' at operation index 2.
@sidetree/core:       at OperationProcessor.<anonymous> (src/OperationProcessor.ts:94:17)
@sidetree/core:     console.debug
@sidetree/core:       Ignored invalid operation for DID 'EiDdKdJEWztnVTCy2cFH6y11kbQsIBi6VJ-_3yH8h6BncA' in transaction '2' at time '2' at operation index 2.
@sidetree/core:       at OperationProcessor.<anonymous> (src/OperationProcessor.ts:94:17)
@sidetree/core: Test Suites: 29 passed, 29 total
@sidetree/core: Tests:       259 passed, 259 total
@sidetree/core: Snapshots:   0 total
@sidetree/core: Time:        17.73s, estimated 28s
@sidetree/core: Ran all test suites.
lerna success run Ran npm script 'test' in 1 package in 23.6s:
lerna success - @sidetree/core
```

**Comment by gjgd** [comment]
Hi @devrajsinghrawat ! From the logs you're showing it looks like all the tests are passing.

The console.errors that you are seeing are due to testing failure cases and are normal.

You should be concerned if you see a `FAIL` in the logs

**Comment by devrajsinghrawat** [comment]
@gjgd Noted , I ll check it again, Keeping your comments in mind.
